# apply name 应用名
config.SelectRunFileConfig=BrownDust II.exe
# Image path 图片地址（默认本地文件项目目录：${project}/BD2AutomaticDecompositionEquipment/BD2Automatic/images/Equipmentdecomposition/）
config.ImagePath=/BD2Automatic/images/
# Match expected values 匹配值(默认0.8)
config.MatchThreshold=0.8

